# Generated by Django 5.2.7 on 2025-10-16 22:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('COMPUTERS', 'Computers & Accessories'), ('CLOTHING', 'Clothing, Shoes & Jewelry'), ('HOME', 'Home & Kitchen'), ('BOOKS', 'Books'), ('TOYS', 'Toys & Games'), ('BEAUTY', 'Beauty & Personal Care'), ('SPORTS', 'Sports & Outdoors'), ('AUTOMOTIVE', 'Automotive'), ('TOOLS', 'Tools & Home Improvement'), ('HEALTH', 'Health & Household'), ('CELLPHONES', 'Cell Phones & Accessories'), ('PETS', 'Pet Supplies'), ('VIDEO_GAMES', 'Video Games'), ('OFFICE', 'Office Products'), ('GARDEN', 'Patio, Lawn & Garden'), ('MUSIC', 'Musical Instruments'), ('COLLECTIBLES', 'Collectibles & Fine Art'), ('MISCELLANEOUS', 'Miscellaneous')], default='MISCELLANEOUS')),
                ('condition', models.CharField(choices=[('USED', 'Used'), ('NEW', 'New')], default='NEW', max_length=4)),
                ('manufacture_year', models.IntegerField(blank=True, help_text='Enter a year between 1582 and the current year', null=True, validators=[django.core.validators.MinValueValidator(1582), django.core.validators.MaxValueValidator(2026)])),
                ('country_of_origin', models.CharField(blank=True, max_length=40, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField()),
                ('initial_bid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('bid_history_json', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
