# Generated by Django 5.2.7 on 2025-10-16 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='final_bidder',
        ),
        migrations.AddField(
            model_name='item',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
