# Generated by Django 5.2.7 on 2025-10-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_highest_bidder_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('COMPUTERS', 'Computers & Accessories'), ('CLOTHING', 'Clothing, Shoes & Jewelry'), ('HOME', 'Home & Kitchen'), ('BOOKS', 'Books'), ('TOYS', 'Toys & Games'), ('BEAUTY', 'Beauty & Personal Care'), ('SPORTS', 'Sports & Outdoors'), ('AUTOMOTIVE', 'Automotive'), ('TOOLS', 'Tools & Home Improvement'), ('HEALTH', 'Health & Household'), ('CELLPHONES', 'Cell Phones & Accessories'), ('PETS', 'Pet Supplies'), ('VIDEO_GAMES', 'Video Games'), ('OFFICE', 'Office Products'), ('GARDEN', 'Patio, Lawn & Garden'), ('MUSIC', 'Musical Instruments'), ('COLLECTIBLES', 'Collectibles & Fine Art'), ('MISCELLANEOUS', 'Miscellaneous')], db_index=True, default='MISCELLANEOUS'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('USED', 'Used'), ('NEW', 'New')], db_index=True, default='NEW', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
