# Generated by Django 5.2.7 on 2025-10-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_category_alter_item_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
