# Generated by Django 5.2.7 on 2025-10-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='payment_confirmation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
