# Generated by Django 5.2.7 on 2025-10-25 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
