# Generated by Django 5.2.7 on 2025-10-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item_id',
        ),
    ]
