# Generated by Django 5.2.7 on 2025-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
